// Code generated by "stringer -type=Comparison"; DO NOT EDIT.

package kavitaapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Equal-0]
	_ = x[GreaterThan-1]
	_ = x[GreaterThanEqual-2]
	_ = x[LessThan-3]
	_ = x[LessThanEqual-4]
	_ = x[Contains-5]
	_ = x[Matches-6]
	_ = x[NotContains-7]
	_ = x[NotEqual-9]
	_ = x[BeginsWith-10]
	_ = x[EndsWith-11]
	_ = x[IsBefore-12]
	_ = x[IsAfter-13]
	_ = x[IsInLast-14]
	_ = x[IsNotInLast-15]
}

const (
	_Comparison_name_0 = "EqualGreaterThanGreaterThanEqualLessThanLessThanEqualContainsMatchesNotContains"
	_Comparison_name_1 = "NotEqualBeginsWithEndsWithIsBeforeIsAfterIsInLastIsNotInLast"
)

var (
	_Comparison_index_0 = [...]uint8{0, 5, 16, 32, 40, 53, 61, 68, 79}
	_Comparison_index_1 = [...]uint8{0, 8, 18, 26, 34, 41, 49, 60}
)

func (i Comparison) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _Comparison_name_0[_Comparison_index_0[i]:_Comparison_index_0[i+1]]
	case 9 <= i && i <= 15:
		i -= 9
		return _Comparison_name_1[_Comparison_index_1[i]:_Comparison_index_1[i+1]]
	default:
		return "Comparison(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
