// Code generated by "stringer -type=FilterField"; DO NOT EDIT.

package kavitaapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Summary-0]
	_ = x[SeriesName-1]
	_ = x[PublicationStatus-2]
	_ = x[Languages-3]
	_ = x[AgeRating-4]
	_ = x[UserRating-5]
	_ = x[Tags-6]
	_ = x[CollectionTags-7]
	_ = x[Translators-8]
	_ = x[Characters-9]
	_ = x[Publisher-10]
	_ = x[Editor-11]
	_ = x[CoverArtist-12]
	_ = x[Letterer-13]
	_ = x[Colorist-14]
	_ = x[Inker-15]
	_ = x[Penciller-16]
	_ = x[Writers-17]
	_ = x[Genres-18]
	_ = x[Libraries-19]
	_ = x[ReadProgress-20]
	_ = x[Formats-21]
	_ = x[ReleaseYear-22]
	_ = x[ReadTime-23]
}

const _FilterField_name = "SummarySeriesNamePublicationStatusLanguagesAgeRatingUserRatingTagsCollectionTagsTranslatorsCharactersPublisherEditorCoverArtistLettererColoristInkerPencillerWritersGenresLibrariesReadProgressFormatsReleaseYearReadTime"

var _FilterField_index = [...]uint8{0, 7, 17, 34, 43, 52, 62, 66, 80, 91, 101, 110, 116, 127, 135, 143, 148, 157, 164, 170, 179, 191, 198, 209, 217}

func (i FilterField) String() string {
	if i < 0 || i >= FilterField(len(_FilterField_index)-1) {
		return "FilterField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterField_name[_FilterField_index[i]:_FilterField_index[i+1]]
}
