// Code generated by "stringer -type=FilterCombination"; DO NOT EDIT.

package kavitaapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Or-0]
	_ = x[And-1]
}

const _FilterCombination_name = "OrAnd"

var _FilterCombination_index = [...]uint8{0, 2, 5}

func (i FilterCombination) String() string {
	if i < 0 || i >= FilterCombination(len(_FilterCombination_index)-1) {
		return "FilterCombination(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterCombination_name[_FilterCombination_index[i]:_FilterCombination_index[i+1]]
}
